Для веб-приложения использовал простой Hello-World написанный на Go (hello.go) и сервер nginx


apiVersion: apps/v1
kind: Deployment            
metadata:               
  name: myservice        имя сервиса
spec:
  replicas: 5            количество реплик сервиса
  selector:
    matchLabels:
      appname: web       метка по которым будем следить за количеством реплик
  template:              шаблон
    metadata:
      name: nginx
      labels:
        appname: web
    spec:
      containers:
      - name: nginx              
        image: nginx:latest             установка nginx
        volumeMounts:                       
        - name: config-nginx                подключение configmap
          mountPath: /etc/nginx/conf.d/     вот по этому пути
      - name: site                        
        image: containous/site              запуск второго образа hello.go
    volumes:
      - name: config-nginx                  отсюда берет данные которые подключаются Mountpath
        configMap:
           name: nginx-config

apiVersion: v1
kind: service
metadata:
  name: nginx-service
spec: 
  selector:
    appname: web
  ports:
      - protocol: TCP
        port: 80 
        targetPort: 80

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myservice
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myservice
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

apiVersion: v1  
kind: ResourceQuota  
metadata:  
  name: quota  
spec:  
  hard:
    limits.cpu: "4"  
    limits.memory: 1Gi
